### ISSUE TITLE
Atualizar doações

### ISSUE THREAD

**Issue by cintiamcr** [brcontraovirus/brcontraovirus.github.io#109]
Doações de máscaras do mês de abril:

- [x] Hospital Infantil Darcy Vargas	200
- [x] GRAACC	100
- [x] SAMU PMSP	63
- [x] INST. DE TRATAMENTO DO CANCER INFANTIL	40
- [ ] H. DE CAMPANHA: TABOÃO DA SERRA	60
- [ ] HOSPITAL ALEXANDRE ZAIO	150
- [ ] MUNICIPAL DOUTOR CARMINO CARICCHIO	150
- [ ] HOSPITAL DO PIRAJUSSARA	300
- [ ] POLICIA CIVIL DO ESTADO DE SP	50
- [ ] Hospital Cachoeirinha	30
- [ ] Hospital Mandaqui	30
- [ ] Supervisao tecnica saude casa verde	50
- [ ] PS Central de São Bernardo do Campo	60
- [ ] Hospital das Clínicas	100
- [ ] Hospital Geral de Guarulhos	40
- [ ] Hospital São Paulo	40
- [ ] Hospital Geral de Mogi das Cruzes	40
- [ ] PS Ipiranga - Hospital do Ipiranga	60
- [ ] Medico Sem Fronteiras	210
- [ ] Hospital Várzea do Carmo - COVID capital3	50

**Comment by thaismartinsprojects** [comment]
@cintiamcr qual o valor correto para o `Hospital das Clínicas` 40 ou 60?

**Comment by thaismartinsprojects** [comment]
@cintiamcr qual o valor correto para o `Medico Sem Fronteiras` é 10 ou 200?

**Comment by cintiamcr** [comment]
> @cintiamcr qual o valor correto para o `Hospital das Clínicas` 40 ou 60?
100

> @cintiamcr qual o valor correto para o `Medico Sem Fronteiras` é 10 ou 200?
210

**Comment by cintiamcr** [comment]
Todos os que estiverem repetidos (inclusive os que já estão no site), é pra somar.

**Comment by thaismartinsprojects** [comment]
Só para ver se eu entendi mesmo, por exemplo: se no site o GRAAC estiver com 50 unidades e aqui estiver 100, eu preciso atualizar a doação para 150, é isso?

**Comment by cintiamcr** [comment]
> @cintiamcr, só para ver se eu entendi mesmo, por exemplo: se no site o GRAAC estiver com 50 unidades e aqui estiver 100, eu preciso atualizar a doação para 150, é isso?

Isso mesmo.
