### ISSUE TITLE
Aumentar o tempo de cache para recursos estáticos

### ISSUE THREAD

**Issue by iecker** [brcontraovirus/brcontraovirus.github.io#20]
Teste do Google PageSpeed Insights recomenda uso de cache para conteúdo estático com max-age de 1 ano ou mais.

https://developers.google.com/speed/pagespeed/insights/?hl=pt-br&url=https%3A%2F%2Fbrasilcontraovirus.com%2F&tab=desktop

![image](https://user-images.githubusercontent.com/3716/79678154-adf54580-81ce-11ea-89a5-e066fc5bd40e.png)

**Comment by ocordeiro** [comment]
Excelente. Aumentei pra 60 dias
