### ISSUE TITLE
Configurar conta no Google Analytics

### ISSUE THREAD

**Issue by cintiamcr** [brcontraovirus/brcontraovirus.github.io#65]
## O que deve ser feito? :thinking:
- [x] Configurar propriedade
- [x] Configurar vistas
- [x] Incluir arquivo de verificação de propriedade

## Como? :page_with_curl:
-  [Google Analytics for Beginners](https://analytics.google.com/analytics/academy/course/6?hl=pt-BR)
- [Advanced Google Analytics](https://analytics.google.com/analytics/academy/course/7?hl=pt-BR)

**Comment by thaismartinsprojects** [comment]
@cintiamcr podemos fechar essa issue?
