### ISSUE TITLE
Alterar texto e imagem do banner principal

### ISSUE THREAD

**Issue by cintiamcr** [brcontraovirus/brcontraovirus.github.io#8]
> Saiba como contribuir para continuarmos produzindo e doando máscaras de proteção destinada aos profissionais de saúde pública na linha de frente em combate ao Covid-19.

[Brasil Contra o Vírus - Precisamos de Você.pdf](https://github.com/brcontraovirus/brcontraovirus.github.io/files/4484683/Brasil.Contra.o.Virus.-.Precisamos.de.Voce.pdf)

**Comment by cintiamcr** [comment]
![20200416_142812](https://user-images.githubusercontent.com/60197222/79488587-5600e800-7ff0-11ea-8e1c-69407c7756d2.jpg)

**Comment by iecker** [comment]
É para trocar essa parte pela imagem acima e pelo texto (Saiba como contribuir para continuarmos produzindo e doando máscaras de proteção destinada aos profissionais de saúde pública na linha de frente em combate ao Covid-19.)?

E o PDF?

![image](https://user-images.githubusercontent.com/3716/79672116-8e95f280-81a5-11ea-8d9d-5a48f91c0c76.png)

**Comment by cintiamcr** [comment]
> É para trocar essa parte pela imagem acima e pelo texto (Saiba como contribuir para continuarmos produzindo e doando máscaras de proteção destinada aos profissionais de saúde pública na linha de frente em combate ao Covid-19.)?

Isso. Pode ignorar o pdf.
